name: Update package versions

on:
  push:
    tags:
      - v2.*
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.head.ref }}

      - name: Find newest annotated tag
        id: newest-tag
        run: |
          latest_annotated_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Newest annotated tag: $latest_annotated_tag"
          echo "latest_annotated_tag=$latest_annotated_tag" >> $GITHUB_OUTPUT

      - name: Check if tag is valid version
        id: valid-tag
        run: |
          latest_annotated_tag="${{ steps.newest-tag.outputs.latest_annotated_tag }}"
          echo "Passed value: $latest_annotated_tag"
          if [[ $latest_annotated_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Valid tag format"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "Invalid tag format"
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Update package versions
        if: steps.valid-tag.outputs.valid
        run: |
          latest_annotated_tag="${{ steps.newest-tag.outputs.latest_annotated_tag }}"
          latest_annotated_tag_without_v="${latest_annotated_tag#v}"  # Remove 'v' prefix
          echo "$latest_annotated_tag_without_v" > VERSION
          sed -i "s/^Version:.*$/Version:        $latest_annotated_tag_without_v/" package/rpm/m8c.spec
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git commit -am "Update package versions to $latest_annotated_tag_without_v"
          git push origin HEAD:main
